//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeRateService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exception.enterpriseservice.mincom.com")]
    public partial class EnterpriseServiceOperationException
    {
        
        private ErrorMessageDTO[] errorMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://ellipse.enterpriseservice.mincom.com")]
        public ErrorMessageDTO[] errorMessages
        {
            get
            {
                return this.errorMessagesField;
            }
            set
            {
                this.errorMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ellipse.enterpriseservice.mincom.com")]
    public partial class ErrorMessageDTO : ApplicationMessageImpl
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ErrorMessageDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WarningMessageDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ellipse.enterpriseservice.mincom.com")]
    public partial class ApplicationMessageImpl
    {
        
        private string codeField;
        
        private int dtoIndexField;
        
        private bool dtoIndexFieldSpecified;
        
        private int fieldIndexField;
        
        private bool fieldIndexFieldSpecified;
        
        private string fieldNameField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int dtoIndex
        {
            get
            {
                return this.dtoIndexField;
            }
            set
            {
                this.dtoIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtoIndexSpecified
        {
            get
            {
                return this.dtoIndexFieldSpecified;
            }
            set
            {
                this.dtoIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int fieldIndex
        {
            get
            {
                return this.fieldIndexField;
            }
            set
            {
                this.fieldIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fieldIndexSpecified
        {
            get
            {
                return this.fieldIndexFieldSpecified;
            }
            set
            {
                this.fieldIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string fieldName
        {
            get
            {
                return this.fieldNameField;
            }
            set
            {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateServiceCurrencyConvertReplyCollectionDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ellipse.enterpriseservice.mincom.com")]
    public abstract partial class AbstractReplyCollectionDTO
    {
        
        private string collectionRestartPointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string collectionRestartPoint
        {
            get
            {
                return this.collectionRestartPointField;
            }
            set
            {
                this.collectionRestartPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com")]
    public partial class ExchangeRateServiceCurrencyConvertReplyCollectionDTO : AbstractReplyCollectionDTO
    {
        
        private ExchangeRateServiceCurrencyConvertReplyDTO[] replyElementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ExchangeRateServiceCurrencyConvertReplyDTO[] replyElements
        {
            get
            {
                return this.replyElementsField;
            }
            set
            {
                this.replyElementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com")]
    public partial class ExchangeRateServiceCurrencyConvertReplyDTO : AbstractReplyDTO
    {
        
        private string fromCurrencyField;
        
        private decimal fromValueField;
        
        private bool fromValueFieldSpecified;
        
        private decimal localBuyRateField;
        
        private bool localBuyRateFieldSpecified;
        
        private decimal localBuyValueField;
        
        private bool localBuyValueFieldSpecified;
        
        private string localCurrencyField;
        
        private decimal localNatRateField;
        
        private bool localNatRateFieldSpecified;
        
        private decimal localNatValueField;
        
        private bool localNatValueFieldSpecified;
        
        private decimal localSellRateField;
        
        private bool localSellRateFieldSpecified;
        
        private decimal localSellValueField;
        
        private bool localSellValueFieldSpecified;
        
        private decimal nominateBuyRateField;
        
        private bool nominateBuyRateFieldSpecified;
        
        private decimal nominateBuyValueField;
        
        private bool nominateBuyValueFieldSpecified;
        
        private string nominateCurrencyField;
        
        private decimal nominateNatRateField;
        
        private bool nominateNatRateFieldSpecified;
        
        private decimal nominateNatValueField;
        
        private bool nominateNatValueFieldSpecified;
        
        private decimal nominateSellRateField;
        
        private bool nominateSellRateFieldSpecified;
        
        private decimal nominateSellValueField;
        
        private bool nominateSellValueFieldSpecified;
        
        private decimal secondBuyRateField;
        
        private bool secondBuyRateFieldSpecified;
        
        private decimal secondBuyValueField;
        
        private bool secondBuyValueFieldSpecified;
        
        private string secondCurrencyField;
        
        private decimal secondNatRateField;
        
        private bool secondNatRateFieldSpecified;
        
        private decimal secondNatValueField;
        
        private bool secondNatValueFieldSpecified;
        
        private decimal secondSellRateField;
        
        private bool secondSellRateFieldSpecified;
        
        private decimal secondSellValueField;
        
        private bool secondSellValueFieldSpecified;
        
        private string transactionDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fromCurrency
        {
            get
            {
                return this.fromCurrencyField;
            }
            set
            {
                this.fromCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal fromValue
        {
            get
            {
                return this.fromValueField;
            }
            set
            {
                this.fromValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromValueSpecified
        {
            get
            {
                return this.fromValueFieldSpecified;
            }
            set
            {
                this.fromValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal localBuyRate
        {
            get
            {
                return this.localBuyRateField;
            }
            set
            {
                this.localBuyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localBuyRateSpecified
        {
            get
            {
                return this.localBuyRateFieldSpecified;
            }
            set
            {
                this.localBuyRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal localBuyValue
        {
            get
            {
                return this.localBuyValueField;
            }
            set
            {
                this.localBuyValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localBuyValueSpecified
        {
            get
            {
                return this.localBuyValueFieldSpecified;
            }
            set
            {
                this.localBuyValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string localCurrency
        {
            get
            {
                return this.localCurrencyField;
            }
            set
            {
                this.localCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal localNatRate
        {
            get
            {
                return this.localNatRateField;
            }
            set
            {
                this.localNatRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localNatRateSpecified
        {
            get
            {
                return this.localNatRateFieldSpecified;
            }
            set
            {
                this.localNatRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal localNatValue
        {
            get
            {
                return this.localNatValueField;
            }
            set
            {
                this.localNatValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localNatValueSpecified
        {
            get
            {
                return this.localNatValueFieldSpecified;
            }
            set
            {
                this.localNatValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal localSellRate
        {
            get
            {
                return this.localSellRateField;
            }
            set
            {
                this.localSellRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localSellRateSpecified
        {
            get
            {
                return this.localSellRateFieldSpecified;
            }
            set
            {
                this.localSellRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal localSellValue
        {
            get
            {
                return this.localSellValueField;
            }
            set
            {
                this.localSellValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localSellValueSpecified
        {
            get
            {
                return this.localSellValueFieldSpecified;
            }
            set
            {
                this.localSellValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal nominateBuyRate
        {
            get
            {
                return this.nominateBuyRateField;
            }
            set
            {
                this.nominateBuyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nominateBuyRateSpecified
        {
            get
            {
                return this.nominateBuyRateFieldSpecified;
            }
            set
            {
                this.nominateBuyRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal nominateBuyValue
        {
            get
            {
                return this.nominateBuyValueField;
            }
            set
            {
                this.nominateBuyValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nominateBuyValueSpecified
        {
            get
            {
                return this.nominateBuyValueFieldSpecified;
            }
            set
            {
                this.nominateBuyValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string nominateCurrency
        {
            get
            {
                return this.nominateCurrencyField;
            }
            set
            {
                this.nominateCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal nominateNatRate
        {
            get
            {
                return this.nominateNatRateField;
            }
            set
            {
                this.nominateNatRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nominateNatRateSpecified
        {
            get
            {
                return this.nominateNatRateFieldSpecified;
            }
            set
            {
                this.nominateNatRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal nominateNatValue
        {
            get
            {
                return this.nominateNatValueField;
            }
            set
            {
                this.nominateNatValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nominateNatValueSpecified
        {
            get
            {
                return this.nominateNatValueFieldSpecified;
            }
            set
            {
                this.nominateNatValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal nominateSellRate
        {
            get
            {
                return this.nominateSellRateField;
            }
            set
            {
                this.nominateSellRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nominateSellRateSpecified
        {
            get
            {
                return this.nominateSellRateFieldSpecified;
            }
            set
            {
                this.nominateSellRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal nominateSellValue
        {
            get
            {
                return this.nominateSellValueField;
            }
            set
            {
                this.nominateSellValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nominateSellValueSpecified
        {
            get
            {
                return this.nominateSellValueFieldSpecified;
            }
            set
            {
                this.nominateSellValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal secondBuyRate
        {
            get
            {
                return this.secondBuyRateField;
            }
            set
            {
                this.secondBuyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondBuyRateSpecified
        {
            get
            {
                return this.secondBuyRateFieldSpecified;
            }
            set
            {
                this.secondBuyRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal secondBuyValue
        {
            get
            {
                return this.secondBuyValueField;
            }
            set
            {
                this.secondBuyValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondBuyValueSpecified
        {
            get
            {
                return this.secondBuyValueFieldSpecified;
            }
            set
            {
                this.secondBuyValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string secondCurrency
        {
            get
            {
                return this.secondCurrencyField;
            }
            set
            {
                this.secondCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal secondNatRate
        {
            get
            {
                return this.secondNatRateField;
            }
            set
            {
                this.secondNatRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondNatRateSpecified
        {
            get
            {
                return this.secondNatRateFieldSpecified;
            }
            set
            {
                this.secondNatRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal secondNatValue
        {
            get
            {
                return this.secondNatValueField;
            }
            set
            {
                this.secondNatValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondNatValueSpecified
        {
            get
            {
                return this.secondNatValueFieldSpecified;
            }
            set
            {
                this.secondNatValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal secondSellRate
        {
            get
            {
                return this.secondSellRateField;
            }
            set
            {
                this.secondSellRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondSellRateSpecified
        {
            get
            {
                return this.secondSellRateFieldSpecified;
            }
            set
            {
                this.secondSellRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal secondSellValue
        {
            get
            {
                return this.secondSellValueField;
            }
            set
            {
                this.secondSellValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondSellValueSpecified
        {
            get
            {
                return this.secondSellValueFieldSpecified;
            }
            set
            {
                this.secondSellValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string transactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateServiceCurrencyConvertReplyDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ellipse.enterpriseservice.mincom.com")]
    public abstract partial class AbstractReplyDTO : AbstractDTO
    {
        
        private WarningMessageDTO[] warningsAndInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public WarningMessageDTO[] warningsAndInformation
        {
            get
            {
                return this.warningsAndInformationField;
            }
            set
            {
                this.warningsAndInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ellipse.enterpriseservice.mincom.com")]
    public partial class WarningMessageDTO : ApplicationMessageImpl
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractReplyDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateServiceCurrencyConvertReplyDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateServiceCurrencyConvertRequestDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ellipse.enterpriseservice.mincom.com")]
    public abstract partial class AbstractDTO
    {
        
        private Attribute[] customAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://attribute.ellipse.mincom.com")]
        public Attribute[] customAttributes
        {
            get
            {
                return this.customAttributesField;
            }
            set
            {
                this.customAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://attribute.ellipse.mincom.com")]
    public partial class Attribute
    {
        
        private string nameField;
        
        private string namespaceField;
        
        private anyType2anyTypeMapEntry[] propertiesField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com", IsNullable=false)]
        public anyType2anyTypeMapEntry[] properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com")]
    public partial class anyType2anyTypeMapEntry
    {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com")]
    public partial class ExchangeRateServiceCurrencyConvertRequestDTO : AbstractDTO
    {
        
        private string fromCurrencyField;
        
        private decimal fromValueField;
        
        private bool fromValueFieldSpecified;
        
        private string nominateCurrencyField;
        
        private ExchangeRateServiceCurrencyConvertRequiredAttributesDTO requiredAttributesField;
        
        private string transactionDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fromCurrency
        {
            get
            {
                return this.fromCurrencyField;
            }
            set
            {
                this.fromCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal fromValue
        {
            get
            {
                return this.fromValueField;
            }
            set
            {
                this.fromValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromValueSpecified
        {
            get
            {
                return this.fromValueFieldSpecified;
            }
            set
            {
                this.fromValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nominateCurrency
        {
            get
            {
                return this.nominateCurrencyField;
            }
            set
            {
                this.nominateCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ExchangeRateServiceCurrencyConvertRequiredAttributesDTO requiredAttributes
        {
            get
            {
                return this.requiredAttributesField;
            }
            set
            {
                this.requiredAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string transactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com")]
    public partial class ExchangeRateServiceCurrencyConvertRequiredAttributesDTO : AbstractRequiredAttributesDTO
    {
        
        private bool returnFromCurrencyField;
        
        private bool returnFromCurrencyFieldSpecified;
        
        private bool returnFromValueField;
        
        private bool returnFromValueFieldSpecified;
        
        private bool returnLocalBuyRateField;
        
        private bool returnLocalBuyRateFieldSpecified;
        
        private bool returnLocalBuyValueField;
        
        private bool returnLocalBuyValueFieldSpecified;
        
        private bool returnLocalCurrencyField;
        
        private bool returnLocalCurrencyFieldSpecified;
        
        private bool returnLocalNatRateField;
        
        private bool returnLocalNatRateFieldSpecified;
        
        private bool returnLocalNatValueField;
        
        private bool returnLocalNatValueFieldSpecified;
        
        private bool returnLocalSellRateField;
        
        private bool returnLocalSellRateFieldSpecified;
        
        private bool returnLocalSellValueField;
        
        private bool returnLocalSellValueFieldSpecified;
        
        private bool returnNominateBuyRateField;
        
        private bool returnNominateBuyRateFieldSpecified;
        
        private bool returnNominateBuyValueField;
        
        private bool returnNominateBuyValueFieldSpecified;
        
        private bool returnNominateCurrencyField;
        
        private bool returnNominateCurrencyFieldSpecified;
        
        private bool returnNominateNatRateField;
        
        private bool returnNominateNatRateFieldSpecified;
        
        private bool returnNominateNatValueField;
        
        private bool returnNominateNatValueFieldSpecified;
        
        private bool returnNominateSellRateField;
        
        private bool returnNominateSellRateFieldSpecified;
        
        private bool returnNominateSellValueField;
        
        private bool returnNominateSellValueFieldSpecified;
        
        private bool returnSecondBuyRateField;
        
        private bool returnSecondBuyRateFieldSpecified;
        
        private bool returnSecondBuyValueField;
        
        private bool returnSecondBuyValueFieldSpecified;
        
        private bool returnSecondCurrencyField;
        
        private bool returnSecondCurrencyFieldSpecified;
        
        private bool returnSecondNatRateField;
        
        private bool returnSecondNatRateFieldSpecified;
        
        private bool returnSecondNatValueField;
        
        private bool returnSecondNatValueFieldSpecified;
        
        private bool returnSecondSellRateField;
        
        private bool returnSecondSellRateFieldSpecified;
        
        private bool returnSecondSellValueField;
        
        private bool returnSecondSellValueFieldSpecified;
        
        private bool returnTransactionDateField;
        
        private bool returnTransactionDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool returnFromCurrency
        {
            get
            {
                return this.returnFromCurrencyField;
            }
            set
            {
                this.returnFromCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnFromCurrencySpecified
        {
            get
            {
                return this.returnFromCurrencyFieldSpecified;
            }
            set
            {
                this.returnFromCurrencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool returnFromValue
        {
            get
            {
                return this.returnFromValueField;
            }
            set
            {
                this.returnFromValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnFromValueSpecified
        {
            get
            {
                return this.returnFromValueFieldSpecified;
            }
            set
            {
                this.returnFromValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool returnLocalBuyRate
        {
            get
            {
                return this.returnLocalBuyRateField;
            }
            set
            {
                this.returnLocalBuyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnLocalBuyRateSpecified
        {
            get
            {
                return this.returnLocalBuyRateFieldSpecified;
            }
            set
            {
                this.returnLocalBuyRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool returnLocalBuyValue
        {
            get
            {
                return this.returnLocalBuyValueField;
            }
            set
            {
                this.returnLocalBuyValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnLocalBuyValueSpecified
        {
            get
            {
                return this.returnLocalBuyValueFieldSpecified;
            }
            set
            {
                this.returnLocalBuyValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool returnLocalCurrency
        {
            get
            {
                return this.returnLocalCurrencyField;
            }
            set
            {
                this.returnLocalCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnLocalCurrencySpecified
        {
            get
            {
                return this.returnLocalCurrencyFieldSpecified;
            }
            set
            {
                this.returnLocalCurrencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool returnLocalNatRate
        {
            get
            {
                return this.returnLocalNatRateField;
            }
            set
            {
                this.returnLocalNatRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnLocalNatRateSpecified
        {
            get
            {
                return this.returnLocalNatRateFieldSpecified;
            }
            set
            {
                this.returnLocalNatRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool returnLocalNatValue
        {
            get
            {
                return this.returnLocalNatValueField;
            }
            set
            {
                this.returnLocalNatValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnLocalNatValueSpecified
        {
            get
            {
                return this.returnLocalNatValueFieldSpecified;
            }
            set
            {
                this.returnLocalNatValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool returnLocalSellRate
        {
            get
            {
                return this.returnLocalSellRateField;
            }
            set
            {
                this.returnLocalSellRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnLocalSellRateSpecified
        {
            get
            {
                return this.returnLocalSellRateFieldSpecified;
            }
            set
            {
                this.returnLocalSellRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool returnLocalSellValue
        {
            get
            {
                return this.returnLocalSellValueField;
            }
            set
            {
                this.returnLocalSellValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnLocalSellValueSpecified
        {
            get
            {
                return this.returnLocalSellValueFieldSpecified;
            }
            set
            {
                this.returnLocalSellValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool returnNominateBuyRate
        {
            get
            {
                return this.returnNominateBuyRateField;
            }
            set
            {
                this.returnNominateBuyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnNominateBuyRateSpecified
        {
            get
            {
                return this.returnNominateBuyRateFieldSpecified;
            }
            set
            {
                this.returnNominateBuyRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool returnNominateBuyValue
        {
            get
            {
                return this.returnNominateBuyValueField;
            }
            set
            {
                this.returnNominateBuyValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnNominateBuyValueSpecified
        {
            get
            {
                return this.returnNominateBuyValueFieldSpecified;
            }
            set
            {
                this.returnNominateBuyValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool returnNominateCurrency
        {
            get
            {
                return this.returnNominateCurrencyField;
            }
            set
            {
                this.returnNominateCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnNominateCurrencySpecified
        {
            get
            {
                return this.returnNominateCurrencyFieldSpecified;
            }
            set
            {
                this.returnNominateCurrencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool returnNominateNatRate
        {
            get
            {
                return this.returnNominateNatRateField;
            }
            set
            {
                this.returnNominateNatRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnNominateNatRateSpecified
        {
            get
            {
                return this.returnNominateNatRateFieldSpecified;
            }
            set
            {
                this.returnNominateNatRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool returnNominateNatValue
        {
            get
            {
                return this.returnNominateNatValueField;
            }
            set
            {
                this.returnNominateNatValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnNominateNatValueSpecified
        {
            get
            {
                return this.returnNominateNatValueFieldSpecified;
            }
            set
            {
                this.returnNominateNatValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool returnNominateSellRate
        {
            get
            {
                return this.returnNominateSellRateField;
            }
            set
            {
                this.returnNominateSellRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnNominateSellRateSpecified
        {
            get
            {
                return this.returnNominateSellRateFieldSpecified;
            }
            set
            {
                this.returnNominateSellRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool returnNominateSellValue
        {
            get
            {
                return this.returnNominateSellValueField;
            }
            set
            {
                this.returnNominateSellValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnNominateSellValueSpecified
        {
            get
            {
                return this.returnNominateSellValueFieldSpecified;
            }
            set
            {
                this.returnNominateSellValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool returnSecondBuyRate
        {
            get
            {
                return this.returnSecondBuyRateField;
            }
            set
            {
                this.returnSecondBuyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSecondBuyRateSpecified
        {
            get
            {
                return this.returnSecondBuyRateFieldSpecified;
            }
            set
            {
                this.returnSecondBuyRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool returnSecondBuyValue
        {
            get
            {
                return this.returnSecondBuyValueField;
            }
            set
            {
                this.returnSecondBuyValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSecondBuyValueSpecified
        {
            get
            {
                return this.returnSecondBuyValueFieldSpecified;
            }
            set
            {
                this.returnSecondBuyValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool returnSecondCurrency
        {
            get
            {
                return this.returnSecondCurrencyField;
            }
            set
            {
                this.returnSecondCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSecondCurrencySpecified
        {
            get
            {
                return this.returnSecondCurrencyFieldSpecified;
            }
            set
            {
                this.returnSecondCurrencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool returnSecondNatRate
        {
            get
            {
                return this.returnSecondNatRateField;
            }
            set
            {
                this.returnSecondNatRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSecondNatRateSpecified
        {
            get
            {
                return this.returnSecondNatRateFieldSpecified;
            }
            set
            {
                this.returnSecondNatRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool returnSecondNatValue
        {
            get
            {
                return this.returnSecondNatValueField;
            }
            set
            {
                this.returnSecondNatValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSecondNatValueSpecified
        {
            get
            {
                return this.returnSecondNatValueFieldSpecified;
            }
            set
            {
                this.returnSecondNatValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool returnSecondSellRate
        {
            get
            {
                return this.returnSecondSellRateField;
            }
            set
            {
                this.returnSecondSellRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSecondSellRateSpecified
        {
            get
            {
                return this.returnSecondSellRateFieldSpecified;
            }
            set
            {
                this.returnSecondSellRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool returnSecondSellValue
        {
            get
            {
                return this.returnSecondSellValueField;
            }
            set
            {
                this.returnSecondSellValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSecondSellValueSpecified
        {
            get
            {
                return this.returnSecondSellValueFieldSpecified;
            }
            set
            {
                this.returnSecondSellValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public bool returnTransactionDate
        {
            get
            {
                return this.returnTransactionDateField;
            }
            set
            {
                this.returnTransactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnTransactionDateSpecified
        {
            get
            {
                return this.returnTransactionDateFieldSpecified;
            }
            set
            {
                this.returnTransactionDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateServiceCurrencyConvertRequiredAttributesDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ellipse.enterpriseservice.mincom.com")]
    public abstract partial class AbstractRequiredAttributesDTO
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connectivity.service.ews.mincom.com")]
    public partial class RunAs
    {
        
        private string districtField;
        
        private string positionField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string district
        {
            get
            {
                return this.districtField;
            }
            set
            {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connectivity.service.ews.mincom.com")]
    public partial class OperationContext
    {
        
        private string applicationClientIdField;
        
        private string districtField;
        
        private bool eventDisableField;
        
        private bool eventDisableFieldSpecified;
        
        private int maxInstancesField;
        
        private bool maxInstancesFieldSpecified;
        
        private string positionField;
        
        private bool returnWarningsField;
        
        private bool returnWarningsFieldSpecified;
        
        private RunAs runAsField;
        
        private string tenantIdField;
        
        private bool traceField;
        
        private bool traceFieldSpecified;
        
        private string transactionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string applicationClientId
        {
            get
            {
                return this.applicationClientIdField;
            }
            set
            {
                this.applicationClientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string district
        {
            get
            {
                return this.districtField;
            }
            set
            {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool eventDisable
        {
            get
            {
                return this.eventDisableField;
            }
            set
            {
                this.eventDisableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventDisableSpecified
        {
            get
            {
                return this.eventDisableFieldSpecified;
            }
            set
            {
                this.eventDisableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int maxInstances
        {
            get
            {
                return this.maxInstancesField;
            }
            set
            {
                this.maxInstancesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxInstancesSpecified
        {
            get
            {
                return this.maxInstancesFieldSpecified;
            }
            set
            {
                this.maxInstancesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool returnWarnings
        {
            get
            {
                return this.returnWarningsField;
            }
            set
            {
                this.returnWarningsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnWarningsSpecified
        {
            get
            {
                return this.returnWarningsFieldSpecified;
            }
            set
            {
                this.returnWarningsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public RunAs runAs
        {
            get
            {
                return this.runAsField;
            }
            set
            {
                this.runAsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string tenantId
        {
            get
            {
                return this.tenantIdField;
            }
            set
            {
                this.tenantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool traceSpecified
        {
            get
            {
                return this.traceFieldSpecified;
            }
            set
            {
                this.traceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string transaction
        {
            get
            {
                return this.transactionField;
            }
            set
            {
                this.transactionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com", ConfigurationName="ExchangeRateService.ExchangeRate")]
    public interface ExchangeRate
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExchangeRateService.EnterpriseServiceOperationException), Action="", Name="EnterpriseServiceOperationException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractReplyCollectionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationMessageImpl))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequiredAttributesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExchangeRateServiceCurrencyConvertRequestDTO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateService.multipleCurrencyConvertResponse> multipleCurrencyConvertAsync(ExchangeRateService.multipleCurrencyConvertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ExchangeRateService.EnterpriseServiceOperationException), Action="", Name="EnterpriseServiceOperationException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractReplyCollectionDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationMessageImpl))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequiredAttributesDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExchangeRateServiceCurrencyConvertRequestDTO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateService.currencyConvertResponse> currencyConvertAsync(ExchangeRateService.currencyConvertRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleCurrencyConvert", WrapperNamespace="http://exchangerate.ellipse.enterpriseservice.mincom.com", IsWrapped=true)]
    public partial class multipleCurrencyConvertRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ExchangeRateService.ExchangeRateServiceCurrencyConvertRequestDTO[] requestParameters;
        
        public multipleCurrencyConvertRequest()
        {
        }
        
        public multipleCurrencyConvertRequest(ExchangeRateService.OperationContext context, ExchangeRateService.ExchangeRateServiceCurrencyConvertRequestDTO[] requestParameters)
        {
            this.context = context;
            this.requestParameters = requestParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleCurrencyConvertResponse", WrapperNamespace="http://exchangerate.ellipse.enterpriseservice.mincom.com", IsWrapped=true)]
    public partial class multipleCurrencyConvertResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateService.ExchangeRateServiceCurrencyConvertReplyCollectionDTO @out;
        
        public multipleCurrencyConvertResponse()
        {
        }
        
        public multipleCurrencyConvertResponse(ExchangeRateService.ExchangeRateServiceCurrencyConvertReplyCollectionDTO @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="currencyConvert", WrapperNamespace="http://exchangerate.ellipse.enterpriseservice.mincom.com", IsWrapped=true)]
    public partial class currencyConvertRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateService.ExchangeRateServiceCurrencyConvertRequestDTO requestParameters;
        
        public currencyConvertRequest()
        {
        }
        
        public currencyConvertRequest(ExchangeRateService.OperationContext context, ExchangeRateService.ExchangeRateServiceCurrencyConvertRequestDTO requestParameters)
        {
            this.context = context;
            this.requestParameters = requestParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="currencyConvertResponse", WrapperNamespace="http://exchangerate.ellipse.enterpriseservice.mincom.com", IsWrapped=true)]
    public partial class currencyConvertResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerate.ellipse.enterpriseservice.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateService.ExchangeRateServiceCurrencyConvertReplyDTO @out;
        
        public currencyConvertResponse()
        {
        }
        
        public currencyConvertResponse(ExchangeRateService.ExchangeRateServiceCurrencyConvertReplyDTO @out)
        {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ExchangeRateChannel : ExchangeRateService.ExchangeRate, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ExchangeRateClient : System.ServiceModel.ClientBase<ExchangeRateService.ExchangeRate>, ExchangeRateService.ExchangeRate
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ExchangeRateClient() : 
                base(ExchangeRateClient.GetDefaultBinding(), ExchangeRateClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ExchangeRateServiceHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeRateClient(EndpointConfiguration endpointConfiguration) : 
                base(ExchangeRateClient.GetBindingForEndpoint(endpointConfiguration), ExchangeRateClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeRateClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ExchangeRateClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeRateClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ExchangeRateClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeRateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateService.multipleCurrencyConvertResponse> ExchangeRateService.ExchangeRate.multipleCurrencyConvertAsync(ExchangeRateService.multipleCurrencyConvertRequest request)
        {
            return base.Channel.multipleCurrencyConvertAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateService.multipleCurrencyConvertResponse> multipleCurrencyConvertAsync(ExchangeRateService.OperationContext context, ExchangeRateService.ExchangeRateServiceCurrencyConvertRequestDTO[] requestParameters)
        {
            ExchangeRateService.multipleCurrencyConvertRequest inValue = new ExchangeRateService.multipleCurrencyConvertRequest();
            inValue.context = context;
            inValue.requestParameters = requestParameters;
            return ((ExchangeRateService.ExchangeRate)(this)).multipleCurrencyConvertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateService.currencyConvertResponse> ExchangeRateService.ExchangeRate.currencyConvertAsync(ExchangeRateService.currencyConvertRequest request)
        {
            return base.Channel.currencyConvertAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateService.currencyConvertResponse> currencyConvertAsync(ExchangeRateService.OperationContext context, ExchangeRateService.ExchangeRateServiceCurrencyConvertRequestDTO requestParameters)
        {
            ExchangeRateService.currencyConvertRequest inValue = new ExchangeRateService.currencyConvertRequest();
            inValue.context = context;
            inValue.requestParameters = requestParameters;
            return ((ExchangeRateService.ExchangeRate)(this)).currencyConvertAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ExchangeRateServiceHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ExchangeRateServiceHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("https://dev03-n01-kum.ellipsehosting.com/ews/services/ExchangeRateService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ExchangeRateClient.GetBindingForEndpoint(EndpointConfiguration.ExchangeRateServiceHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ExchangeRateClient.GetEndpointAddress(EndpointConfiguration.ExchangeRateServiceHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ExchangeRateServiceHttpPort,
        }
    }
}
