//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeRateUpdService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", ConfigurationName="ExchangeRateUpdService.ExchangeRateUpd")]
    public interface ExchangeRateUpd
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateUpdService.searchResponse> searchAsync(ExchangeRateUpdService.searchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateUpdService.multipleSaveResponse> multipleSaveAsync(ExchangeRateUpdService.multipleSaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateUpdService.readResponse> readAsync(ExchangeRateUpdService.readRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateUpdService.multipleUpdateResponse> multipleUpdateAsync(ExchangeRateUpdService.multipleUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateUpdService.multipleDeleteResponse> multipleDeleteAsync(ExchangeRateUpdService.multipleDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateUpdService.saveResponse> saveAsync(ExchangeRateUpdService.saveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateUpdService.createResponse> createAsync(ExchangeRateUpdService.createRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateUpdService.updateResponse> updateAsync(ExchangeRateUpdService.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateUpdService.multipleReadResponse> multipleReadAsync(ExchangeRateUpdService.multipleReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateUpdService.deleteResponse> deleteAsync(ExchangeRateUpdService.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Base))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute[]))]
        System.Threading.Tasks.Task<ExchangeRateUpdService.multipleCreateResponse> multipleCreateAsync(ExchangeRateUpdService.multipleCreateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connectivity.service.ews.mincom.com")]
    public partial class OperationContext
    {
        
        private string applicationClientIdField;
        
        private string districtField;
        
        private bool eventDisableField;
        
        private bool eventDisableFieldSpecified;
        
        private int maxInstancesField;
        
        private bool maxInstancesFieldSpecified;
        
        private string positionField;
        
        private bool returnWarningsField;
        
        private bool returnWarningsFieldSpecified;
        
        private RunAs runAsField;
        
        private string tenantIdField;
        
        private bool traceField;
        
        private bool traceFieldSpecified;
        
        private string transactionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string applicationClientId
        {
            get
            {
                return this.applicationClientIdField;
            }
            set
            {
                this.applicationClientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string district
        {
            get
            {
                return this.districtField;
            }
            set
            {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool eventDisable
        {
            get
            {
                return this.eventDisableField;
            }
            set
            {
                this.eventDisableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventDisableSpecified
        {
            get
            {
                return this.eventDisableFieldSpecified;
            }
            set
            {
                this.eventDisableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int maxInstances
        {
            get
            {
                return this.maxInstancesField;
            }
            set
            {
                this.maxInstancesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxInstancesSpecified
        {
            get
            {
                return this.maxInstancesFieldSpecified;
            }
            set
            {
                this.maxInstancesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool returnWarnings
        {
            get
            {
                return this.returnWarningsField;
            }
            set
            {
                this.returnWarningsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnWarningsSpecified
        {
            get
            {
                return this.returnWarningsFieldSpecified;
            }
            set
            {
                this.returnWarningsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public RunAs runAs
        {
            get
            {
                return this.runAsField;
            }
            set
            {
                this.runAsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string tenantId
        {
            get
            {
                return this.tenantIdField;
            }
            set
            {
                this.tenantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool traceSpecified
        {
            get
            {
                return this.traceFieldSpecified;
            }
            set
            {
                this.traceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string transaction
        {
            get
            {
                return this.transactionField;
            }
            set
            {
                this.transactionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://connectivity.service.ews.mincom.com")]
    public partial class RunAs
    {
        
        private string districtField;
        
        private string positionField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string district
        {
            get
            {
                return this.districtField;
            }
            set
            {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Warning))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Error))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://errors.ellipse.mincom.com")]
    public partial class Message
    {
        
        private string fieldIdField;
        
        private int fieldIndexField;
        
        private bool fieldIndexFieldSpecified;
        
        private bool localisableField;
        
        private bool localisableFieldSpecified;
        
        private string messageIdField;
        
        private string messageInstanceField;
        
        private string messageTextField;
        
        private string parentInstanceField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fieldId
        {
            get
            {
                return this.fieldIdField;
            }
            set
            {
                this.fieldIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int fieldIndex
        {
            get
            {
                return this.fieldIndexField;
            }
            set
            {
                this.fieldIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fieldIndexSpecified
        {
            get
            {
                return this.fieldIndexFieldSpecified;
            }
            set
            {
                this.fieldIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool localisable
        {
            get
            {
                return this.localisableField;
            }
            set
            {
                this.localisableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localisableSpecified
        {
            get
            {
                return this.localisableFieldSpecified;
            }
            set
            {
                this.localisableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string messageInstance
        {
            get
            {
                return this.messageInstanceField;
            }
            set
            {
                this.messageInstanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string messageText
        {
            get
            {
                return this.messageTextField;
            }
            set
            {
                this.messageTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string parentInstance
        {
            get
            {
                return this.parentInstanceField;
            }
            set
            {
                this.parentInstanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://errors.ellipse.mincom.com")]
    public partial class Warning : Message
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://errors.ellipse.mincom.com")]
    public partial class Error : Message
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateUpdServiceResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ellipse.mincom.com")]
    public abstract partial class BaseServiceResult
    {
        
        private Error[] errorsField;
        
        private Message[] informationalMessagesField;
        
        private Warning[] warningsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://errors.ellipse.mincom.com")]
        public Error[] errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://errors.ellipse.mincom.com")]
        public Message[] informationalMessages
        {
            get
            {
                return this.informationalMessagesField;
            }
            set
            {
                this.informationalMessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://errors.ellipse.mincom.com")]
        public Warning[] warnings
        {
            get
            {
                return this.warningsField;
            }
            set
            {
                this.warningsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateUpdServiceResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ellipse.mincom.com")]
    public partial class ServiceResult : BaseServiceResult
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
    public partial class ExchangeRateUpdServiceResult : ServiceResult
    {
        
        private ExchangeRateUpdDTO exchangeRateUpdDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExchangeRateUpdDTO exchangeRateUpdDTO
        {
            get
            {
                return this.exchangeRateUpdDTOField;
            }
            set
            {
                this.exchangeRateUpdDTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
    public partial class ExchangeRateUpdDTO : ServiceDTO
    {
        
        private decimal buyingrateField;
        
        private bool buyingrateFieldSpecified;
        
        private System.DateTime currentDateField;
        
        private bool currentDateFieldSpecified;
        
        private string datePerRevsdField;
        
        private string foreignCurrencyField;
        
        private System.DateTime lastModDateField;
        
        private bool lastModDateFieldSpecified;
        
        private string lastModTimeField;
        
        private string lastModUserField;
        
        private string localCurrencyField;
        
        private decimal nationalRateField;
        
        private bool nationalRateFieldSpecified;
        
        private decimal sellingRateField;
        
        private bool sellingRateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal buyingrate
        {
            get
            {
                return this.buyingrateField;
            }
            set
            {
                this.buyingrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool buyingrateSpecified
        {
            get
            {
                return this.buyingrateFieldSpecified;
            }
            set
            {
                this.buyingrateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime currentDate
        {
            get
            {
                return this.currentDateField;
            }
            set
            {
                this.currentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentDateSpecified
        {
            get
            {
                return this.currentDateFieldSpecified;
            }
            set
            {
                this.currentDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string datePerRevsd
        {
            get
            {
                return this.datePerRevsdField;
            }
            set
            {
                this.datePerRevsdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string foreignCurrency
        {
            get
            {
                return this.foreignCurrencyField;
            }
            set
            {
                this.foreignCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime lastModDate
        {
            get
            {
                return this.lastModDateField;
            }
            set
            {
                this.lastModDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModDateSpecified
        {
            get
            {
                return this.lastModDateFieldSpecified;
            }
            set
            {
                this.lastModDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string lastModTime
        {
            get
            {
                return this.lastModTimeField;
            }
            set
            {
                this.lastModTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string lastModUser
        {
            get
            {
                return this.lastModUserField;
            }
            set
            {
                this.lastModUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string localCurrency
        {
            get
            {
                return this.localCurrencyField;
            }
            set
            {
                this.localCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal nationalRate
        {
            get
            {
                return this.nationalRateField;
            }
            set
            {
                this.nationalRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nationalRateSpecified
        {
            get
            {
                return this.nationalRateFieldSpecified;
            }
            set
            {
                this.nationalRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal sellingRate
        {
            get
            {
                return this.sellingRateField;
            }
            set
            {
                this.sellingRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sellingRateSpecified
        {
            get
            {
                return this.sellingRateFieldSpecified;
            }
            set
            {
                this.sellingRateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractSearchParam))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateUpdSearchParam))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateUpdDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ellipse.mincom.com")]
    public abstract partial class ServiceDTO : Base
    {
        
        private Attribute[] customAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://attribute.ellipse.mincom.com")]
        public Attribute[] customAttributes
        {
            get
            {
                return this.customAttributesField;
            }
            set
            {
                this.customAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://attribute.ellipse.mincom.com")]
    public partial class Attribute
    {
        
        private string nameField;
        
        private string namespaceField;
        
        private anyType2anyTypeMapEntry[] propertiesField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsNullable=false)]
        public anyType2anyTypeMapEntry[] properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com")]
    public partial class anyType2anyTypeMapEntry
    {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractSearchParam))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateUpdSearchParam))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateUpdDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://instances.base.types.ellipse.mincom.com")]
    public abstract partial class Base
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExchangeRateUpdSearchParam))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ellipse.mincom.com")]
    public abstract partial class AbstractSearchParam : ServiceDTO
    {
        
        private ServiceRequiredAttributes serviceRequiredAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceRequiredAttributes serviceRequiredAttributes
        {
            get
            {
                return this.serviceRequiredAttributesField;
            }
            set
            {
                this.serviceRequiredAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.ellipse.mincom.com")]
    public partial class ServiceRequiredAttributes
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
    public partial class ExchangeRateUpdSearchParam : AbstractSearchParam
    {
        
        private System.DateTime changedSinceField;
        
        private bool changedSinceFieldSpecified;
        
        private string foreignCurrencyField;
        
        private System.DateTime fromDateField;
        
        private bool fromDateFieldSpecified;
        
        private string localCurrencyField;
        
        private System.DateTime toDateField;
        
        private bool toDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime changedSince
        {
            get
            {
                return this.changedSinceField;
            }
            set
            {
                this.changedSinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSinceSpecified
        {
            get
            {
                return this.changedSinceFieldSpecified;
            }
            set
            {
                this.changedSinceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string foreignCurrency
        {
            get
            {
                return this.foreignCurrencyField;
            }
            set
            {
                this.foreignCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime fromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromDateSpecified
        {
            get
            {
                return this.fromDateFieldSpecified;
            }
            set
            {
                this.fromDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string localCurrency
        {
            get
            {
                return this.localCurrencyField;
            }
            set
            {
                this.localCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime toDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toDateSpecified
        {
            get
            {
                return this.toDateFieldSpecified;
            }
            set
            {
                this.toDateFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="search", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class searchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.ExchangeRateUpdSearchParam searchParams;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.ExchangeRateUpdDTO restart;
        
        public searchRequest()
        {
        }
        
        public searchRequest(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdSearchParam searchParams, ExchangeRateUpdService.ExchangeRateUpdDTO restart)
        {
            this.context = context;
            this.searchParams = searchParams;
            this.restart = restart;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchResponse", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class searchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
        public ExchangeRateUpdService.ExchangeRateUpdServiceResult[] @out;
        
        public searchResponse()
        {
        }
        
        public searchResponse(ExchangeRateUpdService.ExchangeRateUpdServiceResult[] @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleSave", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleSaveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
        public ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos;
        
        public multipleSaveRequest()
        {
        }
        
        public multipleSaveRequest(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos)
        {
            this.context = context;
            this.inputDtos = inputDtos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleSaveResponse", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleSaveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
        public ExchangeRateUpdService.ExchangeRateUpdServiceResult[] @out;
        
        public multipleSaveResponse()
        {
        }
        
        public multipleSaveResponse(ExchangeRateUpdService.ExchangeRateUpdServiceResult[] @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="read", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class readRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO;
        
        public readRequest()
        {
        }
        
        public readRequest(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO)
        {
            this.context = context;
            this.serviceDTO = serviceDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readResponse", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class readResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.ExchangeRateUpdServiceResult @out;
        
        public readResponse()
        {
        }
        
        public readResponse(ExchangeRateUpdService.ExchangeRateUpdServiceResult @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleUpdate", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleUpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
        public ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos;
        
        public multipleUpdateRequest()
        {
        }
        
        public multipleUpdateRequest(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos)
        {
            this.context = context;
            this.inputDtos = inputDtos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleUpdateResponse", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleUpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
        public ExchangeRateUpdService.ExchangeRateUpdServiceResult[] @out;
        
        public multipleUpdateResponse()
        {
        }
        
        public multipleUpdateResponse(ExchangeRateUpdService.ExchangeRateUpdServiceResult[] @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleDelete", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleDeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
        public ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos;
        
        public multipleDeleteRequest()
        {
        }
        
        public multipleDeleteRequest(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos)
        {
            this.context = context;
            this.inputDtos = inputDtos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleDeleteResponse", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleDeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
        public ExchangeRateUpdService.ExchangeRateUpdServiceResult[] @out;
        
        public multipleDeleteResponse()
        {
        }
        
        public multipleDeleteResponse(ExchangeRateUpdService.ExchangeRateUpdServiceResult[] @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class saveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO;
        
        public saveRequest()
        {
        }
        
        public saveRequest(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO)
        {
            this.context = context;
            this.serviceDTO = serviceDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class saveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.ExchangeRateUpdServiceResult @out;
        
        public saveResponse()
        {
        }
        
        public saveResponse(ExchangeRateUpdService.ExchangeRateUpdServiceResult @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class createRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO;
        
        public createRequest()
        {
        }
        
        public createRequest(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO)
        {
            this.context = context;
            this.serviceDTO = serviceDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class createResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.ExchangeRateUpdServiceResult @out;
        
        public createResponse()
        {
        }
        
        public createResponse(ExchangeRateUpdService.ExchangeRateUpdServiceResult @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class updateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO;
        
        public updateRequest()
        {
        }
        
        public updateRequest(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO)
        {
            this.context = context;
            this.serviceDTO = serviceDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class updateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.ExchangeRateUpdServiceResult @out;
        
        public updateResponse()
        {
        }
        
        public updateResponse(ExchangeRateUpdService.ExchangeRateUpdServiceResult @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleRead", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleReadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
        public ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos;
        
        public multipleReadRequest()
        {
        }
        
        public multipleReadRequest(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos)
        {
            this.context = context;
            this.inputDtos = inputDtos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleReadResponse", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleReadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
        public ExchangeRateUpdService.ExchangeRateUpdServiceResult[] @out;
        
        public multipleReadResponse()
        {
        }
        
        public multipleReadResponse(ExchangeRateUpdService.ExchangeRateUpdServiceResult[] @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class deleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO;
        
        public deleteRequest()
        {
        }
        
        public deleteRequest(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO)
        {
            this.context = context;
            this.serviceDTO = serviceDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class deleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.ExchangeRateUpdServiceResult @out;
        
        public deleteResponse()
        {
        }
        
        public deleteResponse(ExchangeRateUpdService.ExchangeRateUpdServiceResult @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleCreate", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleCreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExchangeRateUpdService.OperationContext context;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
        public ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos;
        
        public multipleCreateRequest()
        {
        }
        
        public multipleCreateRequest(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos)
        {
            this.context = context;
            this.inputDtos = inputDtos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multipleCreateResponse", WrapperNamespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", IsWrapped=true)]
    public partial class multipleCreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exchangerateupd.m3901.service.ellipse.mincom.com", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://instances.m3901.types.ellipse.mincom.com")]
        public ExchangeRateUpdService.ExchangeRateUpdServiceResult[] @out;
        
        public multipleCreateResponse()
        {
        }
        
        public multipleCreateResponse(ExchangeRateUpdService.ExchangeRateUpdServiceResult[] @out)
        {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ExchangeRateUpdChannel : ExchangeRateUpdService.ExchangeRateUpd, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ExchangeRateUpdClient : System.ServiceModel.ClientBase<ExchangeRateUpdService.ExchangeRateUpd>, ExchangeRateUpdService.ExchangeRateUpd
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ExchangeRateUpdClient() : 
                base(ExchangeRateUpdClient.GetDefaultBinding(), ExchangeRateUpdClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ExchangeRateUpdServiceHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeRateUpdClient(EndpointConfiguration endpointConfiguration) : 
                base(ExchangeRateUpdClient.GetBindingForEndpoint(endpointConfiguration), ExchangeRateUpdClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeRateUpdClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ExchangeRateUpdClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeRateUpdClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ExchangeRateUpdClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExchangeRateUpdClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateUpdService.searchResponse> ExchangeRateUpdService.ExchangeRateUpd.searchAsync(ExchangeRateUpdService.searchRequest request)
        {
            return base.Channel.searchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateUpdService.searchResponse> searchAsync(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdSearchParam searchParams, ExchangeRateUpdService.ExchangeRateUpdDTO restart)
        {
            ExchangeRateUpdService.searchRequest inValue = new ExchangeRateUpdService.searchRequest();
            inValue.context = context;
            inValue.searchParams = searchParams;
            inValue.restart = restart;
            return ((ExchangeRateUpdService.ExchangeRateUpd)(this)).searchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateUpdService.multipleSaveResponse> ExchangeRateUpdService.ExchangeRateUpd.multipleSaveAsync(ExchangeRateUpdService.multipleSaveRequest request)
        {
            return base.Channel.multipleSaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateUpdService.multipleSaveResponse> multipleSaveAsync(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos)
        {
            ExchangeRateUpdService.multipleSaveRequest inValue = new ExchangeRateUpdService.multipleSaveRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            return ((ExchangeRateUpdService.ExchangeRateUpd)(this)).multipleSaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateUpdService.readResponse> ExchangeRateUpdService.ExchangeRateUpd.readAsync(ExchangeRateUpdService.readRequest request)
        {
            return base.Channel.readAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateUpdService.readResponse> readAsync(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO)
        {
            ExchangeRateUpdService.readRequest inValue = new ExchangeRateUpdService.readRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            return ((ExchangeRateUpdService.ExchangeRateUpd)(this)).readAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateUpdService.multipleUpdateResponse> ExchangeRateUpdService.ExchangeRateUpd.multipleUpdateAsync(ExchangeRateUpdService.multipleUpdateRequest request)
        {
            return base.Channel.multipleUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateUpdService.multipleUpdateResponse> multipleUpdateAsync(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos)
        {
            ExchangeRateUpdService.multipleUpdateRequest inValue = new ExchangeRateUpdService.multipleUpdateRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            return ((ExchangeRateUpdService.ExchangeRateUpd)(this)).multipleUpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateUpdService.multipleDeleteResponse> ExchangeRateUpdService.ExchangeRateUpd.multipleDeleteAsync(ExchangeRateUpdService.multipleDeleteRequest request)
        {
            return base.Channel.multipleDeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateUpdService.multipleDeleteResponse> multipleDeleteAsync(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos)
        {
            ExchangeRateUpdService.multipleDeleteRequest inValue = new ExchangeRateUpdService.multipleDeleteRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            return ((ExchangeRateUpdService.ExchangeRateUpd)(this)).multipleDeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateUpdService.saveResponse> ExchangeRateUpdService.ExchangeRateUpd.saveAsync(ExchangeRateUpdService.saveRequest request)
        {
            return base.Channel.saveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateUpdService.saveResponse> saveAsync(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO)
        {
            ExchangeRateUpdService.saveRequest inValue = new ExchangeRateUpdService.saveRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            return ((ExchangeRateUpdService.ExchangeRateUpd)(this)).saveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateUpdService.createResponse> ExchangeRateUpdService.ExchangeRateUpd.createAsync(ExchangeRateUpdService.createRequest request)
        {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateUpdService.createResponse> createAsync(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO)
        {
            ExchangeRateUpdService.createRequest inValue = new ExchangeRateUpdService.createRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            return ((ExchangeRateUpdService.ExchangeRateUpd)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateUpdService.updateResponse> ExchangeRateUpdService.ExchangeRateUpd.updateAsync(ExchangeRateUpdService.updateRequest request)
        {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateUpdService.updateResponse> updateAsync(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO)
        {
            ExchangeRateUpdService.updateRequest inValue = new ExchangeRateUpdService.updateRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            return ((ExchangeRateUpdService.ExchangeRateUpd)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateUpdService.multipleReadResponse> ExchangeRateUpdService.ExchangeRateUpd.multipleReadAsync(ExchangeRateUpdService.multipleReadRequest request)
        {
            return base.Channel.multipleReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateUpdService.multipleReadResponse> multipleReadAsync(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos)
        {
            ExchangeRateUpdService.multipleReadRequest inValue = new ExchangeRateUpdService.multipleReadRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            return ((ExchangeRateUpdService.ExchangeRateUpd)(this)).multipleReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateUpdService.deleteResponse> ExchangeRateUpdService.ExchangeRateUpd.deleteAsync(ExchangeRateUpdService.deleteRequest request)
        {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateUpdService.deleteResponse> deleteAsync(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO serviceDTO)
        {
            ExchangeRateUpdService.deleteRequest inValue = new ExchangeRateUpdService.deleteRequest();
            inValue.context = context;
            inValue.serviceDTO = serviceDTO;
            return ((ExchangeRateUpdService.ExchangeRateUpd)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExchangeRateUpdService.multipleCreateResponse> ExchangeRateUpdService.ExchangeRateUpd.multipleCreateAsync(ExchangeRateUpdService.multipleCreateRequest request)
        {
            return base.Channel.multipleCreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExchangeRateUpdService.multipleCreateResponse> multipleCreateAsync(ExchangeRateUpdService.OperationContext context, ExchangeRateUpdService.ExchangeRateUpdDTO[] inputDtos)
        {
            ExchangeRateUpdService.multipleCreateRequest inValue = new ExchangeRateUpdService.multipleCreateRequest();
            inValue.context = context;
            inValue.inputDtos = inputDtos;
            return ((ExchangeRateUpdService.ExchangeRateUpd)(this)).multipleCreateAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ExchangeRateUpdServiceHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ExchangeRateUpdServiceHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("https://dev03-n01-kum.ellipsehosting.com/ews/services/ExchangeRateUpdService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ExchangeRateUpdClient.GetBindingForEndpoint(EndpointConfiguration.ExchangeRateUpdServiceHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ExchangeRateUpdClient.GetEndpointAddress(EndpointConfiguration.ExchangeRateUpdServiceHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ExchangeRateUpdServiceHttpPort,
        }
    }
}
